### ISSUE TITLE
Add setting to choose display unit

### ISSUE THREAD

**Issue by cascer1** [leogandmars/nightscout-chrome#1]
Currently the extension always shows BG in mg/dL. I would like to see my values in mmol/L instead.

Either as a setting in the plugin, or by requesting the setting from nightscout would work.

**Comment by leogandmars** [comment]
the unit is now automatically pulled from the user's nightscout site main profile.

**Comment by leogandmars** [comment]
although you can't currently manually choose between mg/dL and mmol/L, it's now always the same as on the user's nightscout site.
