### ISSUE TITLE
Get default alarm on/off state from Nightscout

### ISSUE THREAD

**Issue by cascer1** [leogandmars/nightscout-chrome#14]
In my nightscout environment variables I have set some alarms to disabled. It would be nice if these alarms were also automatically disabled in the plugin.

**Comment by leogandmars** [comment]
This was an accidental change. Reverted in 1.1.5.

(note: you may have to re-enter your site url for this to work. this is to preserve user data and make sure users prior to this update don't get data overwritten.)
