### ISSUE TITLE
Get alarm settings from nightscout API

### ISSUE THREAD

**Issue by cascer1** [leogandmars/nightscout-chrome#2]
Instead of requiring me to copy my alarm values over from Nightscout, it would be nice if the plugin could get them from the API. This way when I change my range in Nightscout, it also updates in the plugin.

**Comment by leogandmars** [comment]
will add support for this soon, since I recently added pulling of unit type (mgdl/mmol) from nightscout profiles this should be relatively easy to implement.

**Comment by leogandmars** [comment]
fixed in 1.1.3
