### ISSUE TITLE
Invalid site URL

### ISSUE THREAD

**Issue by josijojo** [leogandmars/nightscout-chrome#7]
I get the error message: "Invalid site URL". 
The URL works fine in the web browser. 
I have tried with both http and https. 
![image](https://user-images.githubusercontent.com/40074497/50073467-fa92d000-01d8-11e9-869d-fb8c0b5a28ef.png)

**Comment by leogandmars** [comment]
This is due to the fact that the extension only has permissions to access heroku websites. This will be fixed soon, and support for azure websites (in addition to all custom websites) will be added.

**Comment by leogandmars** [comment]
Support for azure websites (and all non-heroku websites) added in 1.1.5
